In [268]:
import numpy as np
import pandas as pd
import math

In [ ]:
# softmax　regression的思路
# softmax regression是logistic regression在多分类上的拓展
# 首先，要给出预测函数，因为我们需要做的事情是对不同的样本，给出其正确的分类，所以我们的预测函数即K个类别对应的估计概率值。
# htheta(x)=[P(y=1|x,theta),
#           p(y=2|x,theta),
#           ……
#           P(y=k|x,theta)]
#          =e/sum(e)
# 第二步，得到了预测函数，我们需要找到合适的损失函数(合适的概念是指函数最好是凸的或者有解析解容易得到最小值的)，使得损失函数最小,这里使用了
# 极大似然估计。
# 极大似然估计：也就相当于argmax,求如何取参数，使得最后可以得到的结果最好
# 代价函数：J(theta)=-[m(sum)i=1K(sum)i1{y(i)=k}log(e/(sum)e)] 公式没法敲，意会一下 很多资料都有这个公式
# 对其求导，使用梯度下降求theta。这里就单纯得使用了全局梯度下降
# softmax 和 logistic regression回归的难点在于如何理解预测函数，损失函数。
# 预测函数就是我们的目的：分类。虽然这俩叫regression 但实际上是分类问题。
# 损失函数就是代价，分错的时候，这个代价越大越好。以此为目标进行构建，常见的有方差，似然估计等等。
# 那么问题来了，为什么logistic regression要叫做logistic呢？
# 就是因为预测函数使用了sigmoid函数。
# 我们再次回到我们的目的上，预测函数是为了分类。那么也就是说，对于不同的类别，预测函数要具有很高的区分度，这样才能方便损失函数区别，最终才能提高准确率。
# 那么sigmoid就不失为一个很好的选择了。我们知道，在x=0的时候，sigmoid的导数是很大的，这个性质使得只要我们的theta将两类分到了x<0和x>0两类，
# 我们的p就会有很大的一个差距。看softmax的代价函数我们知道，当y==k但我们的p(k)很小时，J就会很大，这样是不好的。因此我们要做的是y==k时尽量让这时候的p最大。


In [269]:
train_data = pd.read_csv("E:\\study\\第四年\\知识分析\\逻辑回归\\train.txt",header = None)
test_data = pd.read_csv("E:\\study\\第四年\\知识分析\\逻辑回归\\test.txt", header = None)

In [270]:
def generatefeaturematrix(k,n):
    theta = np.ones((n,k))
    return theta

In [271]:
x_train = (np.matrix(train_data.iloc[:,0:13]))
theta = generatefeaturematrix(3,13)
print(x_train[0]*(1-generateP(theta,x_train[0].T,3)[1]))

[[ 1.01240836 -0.3748332   0.15470169 -0.77972878  1.27593681  0.5393316
   0.68987931 -0.43970874  0.81658932  0.16781123  0.24145152  1.23194638
   0.67533928]]


In [272]:
a = generatefeaturematrix(3,13)
b = generatefeaturematrix(3,1)
a[0] = a[0]-b
print(a)

[[ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [273]:
x_train = (np.matrix(train_data.iloc[:,0:13]).T)
train_data[13]

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
      ..
136    3
137    3
138    3
139    3
140    3
141    3
142    3
143    3
144    3
145    3
146    3
147    3
148    3
149    3
150    3
151    3
152    3
153    3
154    3
155    3
156    3
157    3
158    3
159    3
160    3
161    3
162    3
163    3
164    3
165    3
Name: 13, Length: 166, dtype: int64

In [290]:
def train(k,n,train_data):
    alpha = 0.1#学习率
    epoch = 200#迭代次数
    m = len(train_data)#m代表数据总条数
    
    theta = generatefeaturematrix(k,n)
    x_train = (np.matrix(train_data.iloc[:,0:n]))
    y_train = []
    for i in train_data[n]:
#         #print(i)
#         if i == 'Iris-setosa':
#             y_train.append(0)
#         if i == 'Iris-versicolor':
#             y_train.append(1)
#         if i == 'Iris-virginica':
#             y_train.append(2)  
        y_train.append(i)
    #print(theta)
    #print(y_train)
    #print(x_train)
    #print(x_train[0].shape)
    #print((theta.T)[0])
    for item in range(epoch):
        print("epoch:%d================>"%item)
        print(theta)
        J = generatefeaturematrix(k,n)
        for itemk in range(k):
            #print("itemk:",itemk)
            temp = 0
            for i in range(m):
                #print("itemk:",itemk)
                if itemk == y_train[i]-1:
                    temp += x_train[i]*(1-generateP(theta,x_train[i].T,k)[itemk])
                else:
                    temp += x_train[i]*(0-generateP(theta,x_train[i].T,k)[itemk])
            # print("temp",temp)
            J[:,itemk] = -temp/m
        #print("J:",J)
        theta = theta-alpha*J
    return theta 
    
    
def generateP(theta,x,k):
    P = []
    normal = 0
    for i in range(k):
        P.append(math.exp(np.linalg.det((theta.T)[i]*x)))
        normal += math.exp(np.linalg.det((theta.T)[i]*x))
    for i in range(k):
        #print(i)
        P[i] = P[i]/normal
    #print("P:",P)
    return P

In [291]:
theta = train(3,13,train_data)

epoch:0================>
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
epoch:1================>
[[ 1.03027949  0.964351    1.00536951]
 [ 0.98948137  0.9856927   1.02482593]
 [ 1.01055943  0.98140875  1.00803182]
 [ 0.97530064  1.00792691  1.01677245]
 [ 1.01423958  0.98721595  0.99854447]
 [ 1.02848175  0.99925238  0.97226588]
 [ 1.03152961  1.00333312  0.96513727]
 [ 0.98244016  0.99781675  1.0197431 ]
 [ 1.01779301  1.00287836  0.97932863]
 [ 1.00734781  0.96567854  1.02697365]
 [ 1.0148833   1.01786089  0.96725581]
 [ 1.02369295  1.01165296  0.9646541 ]
 [ 1.03986473  0.97043947  0.9896958 ]]
epoch:2================>
[[ 1.05740868  0.93168661  1.01090471]
 [ 0.9814436   0.97273492  1.04582149]
 [ 1.02034812  0.96450292  1.01514896]
 [ 0.95381667  1.01555398  1.03062935]
 [ 1.02632891  0.97581648  0.99785461]
 [ 1.05220978  0.99859382 

epoch:16================>
[[ 1.26372319  0.66310976  1.07316705]
 [ 0.96229689  0.87363322  1.16406988]
 [ 1.1028253   0.830193    1.0669817 ]
 [ 0.80415905  1.0941221   1.10171885]
 [ 1.0905547   0.90145781  1.00798749]
 [ 1.17894944  0.9932593   0.82779125]
 [ 1.21014401  1.03241783  0.75743817]
 [ 0.8982502   0.99291771  1.10883209]
 [ 1.08636903  1.03554636  0.8780846 ]
 [ 1.07819634  0.68447085  1.23733282]
 [ 1.08048551  1.15845843  0.76105606]
 [ 1.15541322  1.09683556  0.74775122]
 [ 1.32513765  0.71156433  0.96329801]]
epoch:17================>
[[ 1.27263444  0.65092009  1.07644547]
 [ 0.96292063  0.86932829  1.16775108]
 [ 1.10655569  0.82430799  1.06913632]
 [ 0.79780803  1.09840649  1.10378547]
 [ 1.09202304  0.89918708  1.00878988]
 [ 1.18270113  0.99295342  0.82434545]
 [ 1.21521388  1.03366518  0.75112094]
 [ 0.89645335  0.9933971   1.11014955]
 [ 1.08696346  1.03704974  0.8759868 ]
 [ 1.08126497  0.67312999  1.24560504]
 [ 1.08157266  1.16391626  0.75451108]
 [ 1.159190

epoch:32================>
[[ 1.37326676  0.51170129  1.11503195]
 [ 0.97694794  0.82007085  1.20298121]
 [ 1.14938348  0.75703418  1.09358234]
 [ 0.72383203  1.15168032  1.12448765]
 [ 1.10096924  0.88053442  1.01849634]
 [ 1.21868394  0.98838382  0.79293224]
 [ 1.26799841  1.04804178  0.68395981]
 [ 0.88039292  1.00380885  1.11579823]
 [ 1.08708644  1.05345298  0.85946058]
 [ 1.11654371  0.54152512  1.34193117]
 [ 1.08864655  1.22680664  0.68454681]
 [ 1.19965062  1.12712674  0.67322264]
 [ 1.45096537  0.57497975  0.97405488]]
epoch:33================>
[[ 1.37848905  0.50442965  1.1170813 ]
 [ 0.97801098  0.81747501  1.20451401]
 [ 1.15166023  0.75346114  1.09487863]
 [ 0.71984718  1.15467658  1.12547623]
 [ 1.10107884  0.87990048  1.01902068]
 [ 1.22028275  0.98807982  0.79163743]
 [ 1.27058048  1.04879115  0.68062837]
 [ 0.87973183  1.00462065  1.11564752]
 [ 1.0868243   1.05423967  0.85893603]
 [ 1.11839166  0.53450872  1.34709961]
 [ 1.08877568  1.23014626  0.68107805]
 [ 1.201700

epoch:48================>
[[ 1.44421958  0.41289668  1.14288373]
 [ 0.99404253  0.78443485  1.22152261]
 [ 1.18114275  0.7071201   1.11173716]
 [ 0.66818977  1.19415469  1.13765554]
 [ 1.10002075  0.87425219  1.02572706]
 [ 1.23869314  0.98360359  0.77770326]
 [ 1.30251952  1.05815805  0.63932243]
 [ 0.87245763  1.01731413  1.11022824]
 [ 1.08201559  1.06321696  0.85476745]
 [ 1.14166218  0.44450812  1.4138297 ]
 [ 1.08865318  1.27293046  0.63841636]
 [ 1.22772328  1.14074033  0.63153639]
 [ 1.53224519  0.48242504  0.98532977]]
epoch:49================>
[[ 1.44794597  0.40771622  1.1443378 ]
 [ 0.99509421  0.78254223  1.22236356]
 [ 1.18287079  0.70439881  1.1127304 ]
 [ 0.66517414  1.19648659  1.13833927]
 [ 1.09984251  0.87404476  1.02611272]
 [ 1.23965299  0.98331317  0.77703384]
 [ 1.30431572  1.05868521  0.63699908]
 [ 0.87209546  1.01817373  1.10973081]
 [ 1.08167687  1.06366795  0.85465519]
 [ 1.14297952  0.43930991  1.41771057]
 [ 1.08855525  1.27539899  0.63604575]
 [ 1.229224

epoch:64================>
[[ 1.49716784  0.33951879  1.16331337]
 [ 1.01034973  0.75737958  1.23227069]
 [ 1.20644265  0.66722424  1.12633311]
 [ 0.62442821  1.22818118  1.14739061]
 [ 1.09659088  0.8721529   1.03125622]
 [ 1.25164335  0.97911642  0.76924023]
 [ 1.3281378   1.06563649  0.60622571]
 [ 0.86770948  1.03095824  1.10133229]
 [ 1.07680981  1.06897357  0.85421662]
 [ 1.16032442  0.36965537  1.47002021]
 [ 1.08644273  1.308451    0.60510627]
 [ 1.24950298  1.14731107  0.60318596]
 [ 1.59348534  0.4111265   0.99538817]]
epoch:65================>
[[ 1.50007837  0.33550346  1.16441817]
 [ 1.01132901  0.7558836   1.2327874 ]
 [ 1.20788457  0.66494748  1.12716795]
 [ 0.62196527  1.23010636  1.14792836]
 [ 1.09635462  0.87208245  1.03156293]
 [ 1.25231595  0.97884797  0.76883608]
 [ 1.32955796  1.06604847  0.60439357]
 [ 0.86747077  1.03179747  1.10073176]
 [ 1.07650626  1.06924868  0.85424506]
 [ 1.16134586  0.36547849  1.47317566]
 [ 1.08627282  1.31043148  0.6032957 ]
 [ 1.250732

epoch:80================>
[[ 1.53959473  0.28124294  1.17916232]
 [ 1.02543536  0.73551348  1.23905115]
 [ 1.22807012  0.63305624  1.13887364]
 [ 0.58793013  1.25680132  1.15526855]
 [ 1.09280732  0.87144757  1.03574511]
 [ 1.26110333  0.97499714  0.76389953]
 [ 1.34906399  1.07169507  0.57924095]
 [ 0.86441647  1.0441051   1.09147843]
 [ 1.07233292  1.0725626   0.85510448]
 [ 1.17515125  0.30812244  1.51672631]
 [ 1.08351795  1.33761151  0.57887054]
 [ 1.26782844  1.15031603  0.58185553]
 [ 1.64319518  0.35250539  1.00429943]]
epoch:81================>
[[ 1.54199005  0.27797099  1.18003896]
 [ 1.02633765  0.7342762   1.23938615]
 [ 1.22933213  0.63106176  1.13960611]
 [ 0.5858314   1.25845284  1.15571576]
 [ 1.09257604  0.87142476  1.03599919]
 [ 1.26161679  0.97475203  0.76363117]
 [ 1.35026233  1.07204213  0.57769554]
 [ 0.86424141  1.04490543  1.09085316]
 [ 1.07208017  1.07273894  0.8551809 ]
 [ 1.17598387  0.30460703  1.5194091 ]
 [ 1.08332558  1.33927659  0.57739783]
 [ 1.268890

epoch:97================>
[[ 1.57713484  0.23022599  1.19263917]
 [ 1.04016528  0.71611316  1.24372156]
 [ 1.24839262  0.60094323  1.15066415]
 [ 0.55457114  1.28312953  1.16229933]
 [ 1.08905509  0.87122596  1.03971895]
 [ 1.26892613  0.97101843  0.76005544]
 [ 1.36810523  1.07723975  0.55465501]
 [ 0.86178212  1.05734952  1.08086836]
 [ 1.06844434  1.07502881  0.85652686]
 [ 1.18813463  0.25252046  1.55934491]
 [ 1.08020224  1.36394134  0.55585642]
 [ 1.28484404  1.15135862  0.56379734]
 [ 1.68778857  0.29947255  1.01273887]]
epoch:98================>
[[ 1.57915605  0.22749603  1.19334792]
 [ 1.0409931   0.71506878  1.24393813]
 [ 1.2495207   0.59916135  1.15131795]
 [ 0.55274682  1.28457438  1.1626788 ]
 [ 1.08884765  0.87122055  1.0399318 ]
 [ 1.26933441  0.97079636  0.75986923]
 [ 1.36914753  1.07754606  0.55330641]
 [ 0.86164626  1.05810468  1.08024906]
 [ 1.06824125  1.07514456  0.85661419]
 [ 1.1888294   0.24949609  1.5616745 ]
 [ 1.08000644  1.36537333  0.55462023]
 [ 1.285783

epoch:113================>
[[ 1.60745923  0.18946675  1.20307402]
 [ 1.05293824  0.70045987  1.24660189]
 [ 1.26569596  0.57362748  1.16067656]
 [ 0.52689985  1.30510814  1.16799201]
 [ 1.08592633  0.87118733  1.04288635]
 [ 1.2749242   0.96761172  0.75746408]
 [ 1.38394912  1.08194787  0.53410301]
 [ 0.85979566  1.06912097  1.07108336]
 [ 1.06549844  1.07660609  0.85789547]
 [ 1.19850709  0.20681801  1.5946749 ]
 [ 1.07709784  1.38558384  0.53731832]
 [ 1.29919761  1.15116247  0.54963992]
 [ 1.72428665  0.25581628  1.01989707]]
epoch:114================>
[[ 1.60922463  0.18710742  1.20366795]
 [ 1.05370456  0.69955001  1.24674542]
 [ 1.26672861  0.57199858  1.16127281]
 [ 0.52526912  1.30640787  1.16832301]
 [ 1.08574418  0.87118728  1.04306853]
 [ 1.27526526  0.96740867  0.75732606]
 [ 1.3848857   1.08223029  0.53288402]
 [ 0.85968309  1.06983511  1.0704818 ]
 [ 1.0653345   1.07668818  0.85797732]
 [ 1.19910739  0.20413579  1.59675682]
 [ 1.07690665  1.38685439  0.53623896]
 [ 1.3000

epoch:129================>
[[ 1.63417019  0.15393774  1.21189207]
 [ 1.06478645  0.68671911  1.24849444]
 [ 1.28162307  0.54852473  1.1698522 ]
 [ 0.50199546  1.32501835  1.17298619]
 [ 1.08319279  0.87120252  1.04560468]
 [ 1.27999409  0.9644887   0.7555172 ]
 [ 1.39829805  1.0863393   0.51536264]
 [ 0.85812089  1.08025744  1.06162167]
 [ 1.06312532  1.07775233  0.85912235]
 [ 1.20754452  0.16598324  1.62647224]
 [ 1.07409418  1.40493574  0.52097008]
 [ 1.31231581  1.15027906  0.53740513]
 [ 1.75681445  0.21675403  1.02643152]]
epoch:130================>
[[ 1.63573946  0.15186186  1.21239868]
 [ 1.06549899  0.6859138   1.24858721]
 [ 1.28257905  0.54701953  1.17040142]
 [ 0.500517    1.32620464  1.17327836]
 [ 1.08303431  0.87120427  1.04576142]
 [ 1.28028605  0.96430195  0.755412  ]
 [ 1.39915324  1.08660583  0.51424093]
 [ 0.85802416  1.08093353  1.06104231]
 [ 1.06299355  1.07781392  0.85919252]
 [ 1.20807234  0.16356746  1.6283602 ]
 [ 1.07391071  1.40608132  0.52000797]
 [ 1.3131

epoch:146================>
[[ 1.6594824   0.12061428  1.21990332]
 [ 1.07649067  0.67376251  1.24974682]
 [ 1.29731839  0.52383667  1.17884494]
 [ 0.47794243  1.34438423  1.17767334]
 [ 1.08067996  0.87123911  1.04808093]
 [ 1.28462643  0.9614341   0.75393947]
 [ 1.41226441  1.09077092  0.49696467]
 [ 0.85657668  1.09145138  1.05197194]
 [ 1.06111597  1.07868501  0.86019901]
 [ 1.21601286  0.1267913   1.65719584]
 [ 1.07104994  1.42353471  0.50541535]
 [ 1.3251683   1.14887678  0.52595491]
 [ 1.78797921  0.179215    1.03280579]]
epoch:147================>
[[ 1.66088771  0.11877434  1.22033795]
 [ 1.0771533   0.67304542  1.24980128]
 [ 1.29820698  0.52244058  1.17935244]
 [ 0.47659424  1.34547405  1.17793171]
 [ 1.08054358  0.87124164  1.04821478]
 [ 1.28487887  0.9612619   0.75385922]
 [ 1.41305077  1.09102575  0.49592348]
 [ 0.85649176  1.09209068  1.05141756]
 [ 1.061012    1.07873353  0.86025447]
 [ 1.2164801   0.12460134  1.65891857]
 [ 1.07087593  1.42457496  0.5045491 ]
 [ 1.3258

epoch:162================>
[[ 1.68100056  0.09256049  1.22643895]
 [ 1.0867769   0.66281193  1.25041117]
 [ 1.31112171  0.50217034  1.18670795]
 [ 0.45715295  1.36124491  1.18160214]
 [ 1.07863559  0.87128445  1.05007996]
 [ 1.28843838  0.9587674   0.75279422]
 [ 1.42443479  1.09478521  0.48078   ]
 [ 0.85528168  1.10144075  1.04327756]
 [ 1.05961787  1.07940165  0.86098048]
 [ 1.22313142  0.09309731  1.68377127]
 [ 1.06833452  1.43955369  0.49211179]
 [ 1.33642009  1.147287    0.51629291]
 [ 1.81473823  0.14690779  1.03835398]]
epoch:163================>
[[ 1.68228127  0.09089891  1.22681983]
 [ 1.08739831  0.66216228  1.25043942]
 [ 1.3119565   0.50086144  1.18718206]
 [ 0.45590581  1.36226025  1.18183395]
 [ 1.0785171   0.87128765  1.05019525]
 [ 1.28866168  0.95860664  0.75273168]
 [ 1.42516799  1.09503203  0.47979998]
 [ 0.85520484  1.10204867  1.04274649]
 [ 1.05953522  1.07944289  0.86102189]
 [ 1.22355263  0.09108106  1.68536631]
 [ 1.06816967  1.44051328  0.49131705]
 [ 1.3370

epoch:178================>
[[ 1.70069194  0.06711464  1.23219342]
 [ 1.09643963  0.65285168  1.25070869]
 [ 1.32411972  0.48180879  1.19407149]
 [ 0.43785724  1.37700584  1.18513692]
 [ 1.07685812  0.87134172  1.05180016]
 [ 1.29182774  0.95626934  0.75190291]
 [ 1.43581977  1.09868595  0.46549428]
 [ 0.85409987  1.11095012  1.03495001]
 [ 1.05843193  1.08002642  0.86154165]
 [ 1.22957546  0.06196217  1.70846236]
 [ 1.06576457  1.45438633  0.4798491 ]
 [ 1.34697933  1.14553702  0.50748365]
 [ 1.83944108  0.11702992  1.043529  ]]
epoch:179================>
[[ 1.70186923  0.06560021  1.23253055]
 [ 1.09702449  0.65225818  1.25071734]
 [ 1.32490779  0.48057552  1.19451668]
 [ 0.43669548  1.37795839  1.18534613]
 [ 1.076755    0.87134577  1.05189923]
 [ 1.29202742  0.95611816  0.75185442]
 [ 1.43650807  1.09892657  0.46456536]
 [ 0.8540291   1.11152954  1.03444136]
 [ 1.05836689  1.0800634   0.86156971]
 [ 1.2299585   0.06009158  1.70994992]
 [ 1.06560869  1.4552785   0.47911281]
 [ 1.3476

epoch:194================>
[[ 1.71885529  0.04383704  1.23730767]
 [ 1.10554798  0.64372164  1.25073039]
 [ 1.33641375  0.46258587  1.20100038]
 [ 0.41983268  1.39183253  1.18833478]
 [ 1.07530987  0.87141469  1.05327545]
 [ 1.29487126  0.95391254  0.7512162 ]
 [ 1.4465358   1.10249697  0.45096723]
 [ 0.85300404  1.1200231   1.02697286]
 [ 1.0575044   1.08059877  0.86189683]
 [ 1.23545568  0.03298846  1.73155586]
 [ 1.06333545  1.46821949  0.46844505]
 [ 1.35694079  1.14369101  0.4993682 ]
 [ 1.86240974  0.08920891  1.04838136]]
epoch:195================>
[[ 1.71994531  0.04244603  1.23760866]
 [ 1.10610023  0.64317557  1.2507242 ]
 [ 1.33716069  0.46141905  1.20142026]
 [ 0.41874417  1.39273127  1.18852456]
 [ 1.07521995  0.87141986  1.05336019]
 [ 1.29505139  0.95376938  0.75117923]
 [ 1.44718551  1.10273257  0.45008192]
 [ 0.85293793  1.12057658  1.02648549]
 [ 1.05745398  1.08063343  0.86191259]
 [ 1.23580652  0.03124193  1.73295154]
 [ 1.06318816  1.46905436  0.46775748]
 [ 1.3575

In [292]:
def predict(k,n,test_data,theta):
    predictlabel = []
    test = np.matrix(test_data)
    m = len(test)
    for i in range(m):
        temp = np.argmax(test[i]*theta)
        print(temp+1)
#         if temp == 0:
#             print('Iris-setosa')
#             #predictlabel.append('Iris-setosa')
#         if temp == 1:
#             print('Iris-versicolor')
#             #predictlabel.append('Iris-versicolor')
#         if temp == 2:
#             print('Iris-virginica')
#             #predictlabel.append('Iris-virginica')
    #return predictlabel

In [293]:
predict(3,13,test_data,theta)

3
3
3
3
3
1
1
1
1
1
2
2
2
2
2
1
1
1
2
2
2


In [285]:
print(theta.T[0][0],theta.T[0][1],theta.T[0][2],theta.T[0][3],0)
print(theta.T[1][0],theta.T[1][1],theta.T[1][2],theta.T[1][3],0)
print(theta.T[2][0],theta.T[2][1],theta.T[2][2],theta.T[2][3],0)

0.620039036088 -0.696300859632 0.542966233166 -0.143718757574 0
1.34736010778 -0.460305035933 0.915996668535 -0.646441758447 0
-0.21480438688 -0.940387905881 -0.00927873676169 0.435196257105 0


In [294]:
print(theta.T[0],0)
print(theta.T[1],0)
print(theta.T[2],0)

[ 1.72532128  1.10883292  1.34085954  0.4133644   1.07478167  1.29593562
  1.45040087  0.85261113  1.05721411  1.23753343  1.06245949  1.36053799
  1.87062859] 0
[ 0.03559538  0.64048555  0.4556427   1.39717877  0.8714469   0.95306036
  1.10390636  1.12332099  1.08080533  0.02261521  1.47317978  1.14298318
  0.07924496] 0
[ 1.23908334  1.25068152  1.20349776  1.18945683  1.05377143  0.75100402
  0.44569277  1.02406787  0.86198056  1.73985136  0.46436073  0.49647883
  1.05012645] 0
